# Generated by Django 5.1 on 2025-06-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_link_token",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, unique=True
            ),
        ),
    ]
